// Conventional commits, narrowed: extends config-conventional (bodies stay
// optional) and restricts `type`/`scope` to what this repo actually uses.
module.exports = {
	extends: ["@commitlint/config-conventional"],
	rules: {
		"header-max-length": [2, "always", 100],
		"type-enum": [
			2,
			"always",
			[
				"feat",
				"fix",
				"docs",
				"chore",
				"refactor",
				"test",
				"perf",
				"style",
				"build",
				"ci",
			],
		],
		"scope-enum": [
			2,
			"always",
			[
				"auth",
				"users",
				"placement",
				"writing",
				"appeal",
				"voice",
				"exam-simulation",
				"billing",
				"gateway",
				"frontend",
				"worker",
				"ai-service",
				"calibration",
				"pipeline",
				"adaptive-learning",
				"readiness",
				"srs",
				"shared-schemas",
				"infra",
				"deps",
			],
		],
	},
};
