"""initial schema - all Phase 1 entities per Master PRD ERD s29 plus calibration_baselines (Phase 0 Brief s7)

Revision ID: b93033f9cc0b
Revises: 
Create Date: 2026-07-07 22:03:31.382307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b93033f9cc0b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_model_runs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('session_type', sa.String(length=50), nullable=False),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('prompt_hash', sa.String(length=64), nullable=False),
    sa.Column('response_hash', sa.String(length=64), nullable=False),
    sa.Column('input_token_count', sa.Integer(), nullable=False),
    sa.Column('output_token_count', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('streaming_first_token_ms', sa.Integer(), nullable=True),
    sa.Column('was_fallback', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('persona_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('calibration_version', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_model_runs'))
    )
    op.create_index('ix_ai_model_runs_session_id', 'ai_model_runs', ['session_id'], unique=False)
    op.create_table('calibration_baselines',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('calibration_version', sa.String(length=50), nullable=False),
    sa.Column('exam_type', sa.String(length=50), nullable=False),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('overall_pearson', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('category_pearson', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('human_examiner_count', sa.Integer(), nullable=False),
    sa.Column('inter_rater_kappa', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('calibration_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('signed_off_by', sa.String(length=255), nullable=True),
    sa.Column('displayed_on_reports', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_calibration_baselines')),
    sa.UniqueConstraint('calibration_version', 'exam_type', name=op.f('uq_calibration_baselines_calibration_version'))
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Enum('learner', 'admin', 'institution_admin', name='user_role'), server_default='learner', nullable=False),
    sa.Column('subscription_tier', sa.Enum('free', 'pro', name='subscription_tier'), server_default='free', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('gdpr_erasure_requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retraining_opt_out', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('learner_profiles',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('target_language', sa.String(length=10), nullable=False),
    sa.Column('target_exam', sa.String(length=50), nullable=True),
    sa.Column('target_band_score', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('exam_date', sa.Date(), nullable=True),
    sa.Column('accent_target', sa.String(length=10), server_default='en-US', nullable=False),
    sa.Column('default_persona', sa.Enum('companion', 'coach', 'examiner', name='teaching_persona'), server_default='companion', nullable=False),
    sa.Column('active_track', sa.Enum('fluency', 'exam', name='learning_track'), server_default='fluency', nullable=False),
    sa.Column('cefr_speaking', sa.String(length=2), nullable=True),
    sa.Column('cefr_listening', sa.String(length=2), nullable=True),
    sa.Column('cefr_reading', sa.String(length=2), nullable=True),
    sa.Column('cefr_writing', sa.String(length=2), nullable=True),
    sa.Column('placement_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('voice_consent_given', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('onboarding_completed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('weakness_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_learner_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_learner_profiles')),
    sa.UniqueConstraint('user_id', name=op.f('uq_learner_profiles_user_id'))
    )
    op.create_table('daily_sessions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('learner_profile_id', sa.UUID(), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('skill_targeted', sa.String(length=30), nullable=False),
    sa.Column('srs_priority_score', sa.Numeric(precision=5, scale=3), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('pre_session_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('post_session_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('delta_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('readiness_delta', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('ai_model_run_id', sa.UUID(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ai_model_run_id'], ['ai_model_runs.id'], name=op.f('fk_daily_sessions_ai_model_run_id_ai_model_runs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['learner_profile_id'], ['learner_profiles.id'], name=op.f('fk_daily_sessions_learner_profile_id_learner_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_sessions'))
    )
    op.create_index('ix_daily_sessions_learner_date', 'daily_sessions', ['learner_profile_id', 'session_date'], unique=False)
    op.create_table('exam_attempts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('learner_profile_id', sa.UUID(), nullable=False),
    sa.Column('exam_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('in_progress', 'submitted', 'completed', 'abandoned', name='exam_attempt_status'), server_default='in_progress', nullable=False),
    sa.Column('overall_band_score', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('target_band_score', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('readiness_at_attempt', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['learner_profile_id'], ['learner_profiles.id'], name=op.f('fk_exam_attempts_learner_profile_id_learner_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exam_attempts'))
    )
    op.create_table('readiness_snapshots',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('learner_profile_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('readiness_score', sa.Numeric(precision=5, scale=3), nullable=False),
    sa.Column('projected_band_score', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('confidence_interval_low', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('confidence_interval_high', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('trend_factor', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('volatility_factor', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('weighted_skill_average', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('delta_from_previous', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['learner_profile_id'], ['learner_profiles.id'], name=op.f('fk_readiness_snapshots_learner_profile_id_learner_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_readiness_snapshots'))
    )
    op.create_index('ix_readiness_snapshots_learner_date', 'readiness_snapshots', ['learner_profile_id', 'snapshot_date'], unique=False)
    op.create_table('skill_vectors',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('learner_profile_id', sa.UUID(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('grammar_score', sa.Numeric(precision=4, scale=3), server_default='0.500', nullable=False),
    sa.Column('grammar_last_practiced', sa.DateTime(timezone=True), nullable=True),
    sa.Column('grammar_srs_interval', sa.Integer(), server_default='1', nullable=False),
    sa.Column('vocabulary_score', sa.Numeric(precision=4, scale=3), server_default='0.500', nullable=False),
    sa.Column('vocabulary_last_practiced', sa.DateTime(timezone=True), nullable=True),
    sa.Column('vocabulary_srs_interval', sa.Integer(), server_default='1', nullable=False),
    sa.Column('coherence_score', sa.Numeric(precision=4, scale=3), server_default='0.500', nullable=False),
    sa.Column('coherence_last_practiced', sa.DateTime(timezone=True), nullable=True),
    sa.Column('coherence_srs_interval', sa.Integer(), server_default='1', nullable=False),
    sa.Column('pronunciation_score', sa.Numeric(precision=4, scale=3), server_default='0.500', nullable=False),
    sa.Column('pronunciation_last_practiced', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pronunciation_srs_interval', sa.Integer(), server_default='1', nullable=False),
    sa.Column('fluency_score', sa.Numeric(precision=4, scale=3), server_default='0.500', nullable=False),
    sa.Column('fluency_last_practiced', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fluency_srs_interval', sa.Integer(), server_default='1', nullable=False),
    sa.Column('comprehension_score', sa.Numeric(precision=4, scale=3), server_default='0.500', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['learner_profile_id'], ['learner_profiles.id'], name=op.f('fk_skill_vectors_learner_profile_id_learner_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skill_vectors')),
    sa.UniqueConstraint('learner_profile_id', 'language', name=op.f('uq_skill_vectors_learner_profile_id'))
    )
    op.create_table('speaking_sessions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('learner_profile_id', sa.UUID(), nullable=False),
    sa.Column('session_type', sa.Enum('practice', 'placement', 'exam_section', 'daily_diagnostic', name='speaking_session_type'), nullable=False),
    sa.Column('persona_used', sa.Enum('companion', 'coach', 'examiner', name='teaching_persona'), server_default='companion', nullable=False),
    sa.Column('exam_type', sa.String(length=50), nullable=True),
    sa.Column('accent_target', sa.String(length=10), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('socratic_turns_used', sa.Integer(), nullable=True),
    sa.Column('transcript_text', sa.Text(), nullable=True),
    sa.Column('overall_fluency_score', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('overall_pronunciation_score', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('cefr_speaking_level', sa.String(length=2), nullable=True),
    sa.Column('audio_blob_key', sa.String(length=500), nullable=True),
    sa.Column('ai_model_run_id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ai_model_run_id'], ['ai_model_runs.id'], name=op.f('fk_speaking_sessions_ai_model_run_id_ai_model_runs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['learner_profile_id'], ['learner_profiles.id'], name=op.f('fk_speaking_sessions_learner_profile_id_learner_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_speaking_sessions'))
    )
    op.create_table('writing_sessions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('learner_profile_id', sa.UUID(), nullable=False),
    sa.Column('exam_type', sa.String(length=50), nullable=False),
    sa.Column('prompt_text', sa.Text(), nullable=False),
    sa.Column('essay_text', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'scored', 'failed', name='writing_session_status'), server_default='pending', nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('overall_band_score', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('cefr_level', sa.String(length=2), nullable=True),
    sa.Column('calibration_version', sa.String(length=50), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('scored_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['learner_profile_id'], ['learner_profiles.id'], name=op.f('fk_writing_sessions_learner_profile_id_learner_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_writing_sessions'))
    )
    op.create_index('ix_writing_sessions_learner_status', 'writing_sessions', ['learner_profile_id', 'status'], unique=False)
    op.create_table('exam_sections',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('exam_attempt_id', sa.UUID(), nullable=False),
    sa.Column('section_type', sa.String(length=50), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('writing_session_id', sa.UUID(), nullable=True),
    sa.Column('speaking_session_id', sa.UUID(), nullable=True),
    sa.Column('response_text', sa.Text(), nullable=True),
    sa.Column('section_score', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('time_limit_seconds', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['exam_attempt_id'], ['exam_attempts.id'], name=op.f('fk_exam_sections_exam_attempt_id_exam_attempts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['speaking_session_id'], ['speaking_sessions.id'], name=op.f('fk_exam_sections_speaking_session_id_speaking_sessions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['writing_session_id'], ['writing_sessions.id'], name=op.f('fk_exam_sections_writing_session_id_writing_sessions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exam_sections'))
    )
    op.create_table('score_appeals',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('writing_session_id', sa.UUID(), nullable=False),
    sa.Column('learner_profile_id', sa.UUID(), nullable=False),
    sa.Column('appeal_reason', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'processing', 'resolved', name='appeal_status'), server_default='pending', nullable=False),
    sa.Column('original_score', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('secondary_score', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('discrepancy_delta', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('secondary_model_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('requires_human_review', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['learner_profile_id'], ['learner_profiles.id'], name=op.f('fk_score_appeals_learner_profile_id_learner_profiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['writing_session_id'], ['writing_sessions.id'], name=op.f('fk_score_appeals_writing_session_id_writing_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_score_appeals'))
    )
    op.create_table('share_events',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('learner_profile_id', sa.UUID(), nullable=False),
    sa.Column('exam_attempt_id', sa.UUID(), nullable=False),
    sa.Column('band_score_displayed', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('delta_displayed', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('platform', sa.String(length=50), nullable=True),
    sa.Column('card_template_version', sa.String(length=20), nullable=False),
    sa.Column('shared_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exam_attempt_id'], ['exam_attempts.id'], name=op.f('fk_share_events_exam_attempt_id_exam_attempts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['learner_profile_id'], ['learner_profiles.id'], name=op.f('fk_share_events_learner_profile_id_learner_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_share_events'))
    )
    op.create_table('writing_score_breakdowns',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('writing_session_id', sa.UUID(), nullable=False),
    sa.Column('category_1_name', sa.String(length=100), nullable=False),
    sa.Column('category_1_score', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('category_1_weight', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('category_1_feedback', sa.Text(), nullable=True),
    sa.Column('category_2_name', sa.String(length=100), nullable=False),
    sa.Column('category_2_score', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('category_2_weight', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('category_2_feedback', sa.Text(), nullable=True),
    sa.Column('category_3_name', sa.String(length=100), nullable=False),
    sa.Column('category_3_score', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('category_3_weight', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('category_3_feedback', sa.Text(), nullable=True),
    sa.Column('category_4_name', sa.String(length=100), nullable=True),
    sa.Column('category_4_score', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('category_4_weight', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('category_4_feedback', sa.Text(), nullable=True),
    sa.Column('grammar_corrections', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('vocabulary_suggestions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['writing_session_id'], ['writing_sessions.id'], name=op.f('fk_writing_score_breakdowns_writing_session_id_writing_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_writing_score_breakdowns')),
    sa.UniqueConstraint('writing_session_id', name=op.f('uq_writing_score_breakdowns_writing_session_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('writing_score_breakdowns')
    op.drop_table('share_events')
    op.drop_table('score_appeals')
    op.drop_table('exam_sections')
    op.drop_index('ix_writing_sessions_learner_status', table_name='writing_sessions')
    op.drop_table('writing_sessions')
    op.drop_table('speaking_sessions')
    op.drop_table('skill_vectors')
    op.drop_index('ix_readiness_snapshots_learner_date', table_name='readiness_snapshots')
    op.drop_table('readiness_snapshots')
    op.drop_table('exam_attempts')
    op.drop_index('ix_daily_sessions_learner_date', table_name='daily_sessions')
    op.drop_table('daily_sessions')
    op.drop_table('learner_profiles')
    op.drop_table('users')
    op.drop_table('calibration_baselines')
    op.drop_index('ix_ai_model_runs_session_id', table_name='ai_model_runs')
    op.drop_table('ai_model_runs')
    # Native PG enum types are not dropped by drop_table — drop them
    # explicitly so downgrade→upgrade round-trips cleanly.
    for enum_name in (
        "user_role",
        "subscription_tier",
        "teaching_persona",
        "learning_track",
        "writing_session_status",
        "appeal_status",
        "speaking_session_type",
        "exam_attempt_status",
    ):
        op.execute(f'DROP TYPE IF EXISTS {enum_name}')
    # ### end Alembic commands ###
